#dictionary for Si test app
#must add [] if you want dictionary to be indexed
my_dictionary = {
	"K*W*L" : "Helps students activate prior knowledge and link to new information to make connections with what is already known. Title 3 columns: What I Know, What I Want to Know, and What I Learned.Can be used to help focus the session on particular concepts that students are having difficulties with. Towards the end of the session go back to chart and have students go back to K to the column to see if there are any questions left unanswered and then complete the L column.",
	"jigsaw" : "jigsaw_description",
	"1minpaper" : "1minpaper_description",
	"Post Exam Survey" : "The post exam survey is a self-test for students to assess how successfully they studied for an exam. The survey can be used in a SI sessions after an exam to target areas on which students need to improve. The SI leader should tailor a survey to the specific class and emphasize what they feel is important. The leader should assign a specific point value to each survey question that adds up to 100. Then the SI leader should read each question and have the students score themselves based on the specific value for that question. After all the survey questions have been asked, the students should total their score and see how close their survey score is to their exam score. This should lead into a discussion of the most effective way to study for the next exam.",
	"Outline Text Chapter" : "Have students work in groups of 2-4 to make an outline using the headings from an important chapter from the text. Be sure to point out that the size and the placement of the headings are important for determining the main ideas and supporting details. After you have this skeleton outline of the chapter, have the students read to determine the important points under each heading.  If the students have trouble determining the important points, have them turn the headings into questions and then read to find answers. The answers are (most likely) the important points. Who, what, why, when, where, and how are good questions with which to begin. Have groups compare important points with other groups.",
	"Marking the Textbook" : "Working in pairs, ask the students to jot down guidelines for how they currently mark their textbook. In a large group, discuss the following specific to your course: 1. Why read the chapter? 2. What are your goals for reading the chapter? 3. Why mark the text? 4. What do you do with your markings? Then share the pertinent marking textbook suggestions. Have the students compare their markings.",
	"Incomplete Outline" : "Create a set of incomplete lecture notes by making an outline with some of the parts missing. Example: Events that led to WWI 1. 2. The groups must then work through their notes to figure out how to fill in the outline. The incomplete outline is an excellent means of helping the students recognize the main points and the organizational pattern of information given in lecture. It can also be used for the textbook information. Determining the major points can help to sort information and locate the ideas being communicated, making connections easier to find and understand. It helps the students figure out what is important.",
	"Cornell Method of Notetaking" : "Have the students make several sheets of paper using the following directions: 1.	Create a recall column by drawing a vertical line down the page about 1 inch from the margin. 2. Create a summary area by drawing a horizontal line across the page about1 inch from the bottom. Have students take notes in the main area of the page, leaving the left and bottom blank. Ask them to take notes using this format during the next lecture. At the next session you could use the note review strategy to ensure all students have the same important information in their notes. Then have them make up cue questions to put in the recall column. These questions should get at the information in the notes to the right. Be sure students include both general and specific questions in the recall column so they can test themselves on all the information. Finally, have the students write a brief summary of the important material in their notes.",
	"Note Review" : "This is a method of getting the students to work together to review and augment their lecture notes in an organized way. In small groups, have the students take turns reading a portion of his/her motes. Encourage other students to interject with details missed or questions about the topic. Give students time to add information to their notes between turns. Follow up with a short discussion in which students share what note-taking strategies they find effective. Suggest that when students take notes in the lecture they include an “SI questions” in the margin for the aspects in the lecture they would like to discuss in the SI session. Sometimes it is difficult to recall what those questions were if SI sessions are not right after the lecture!",
	"Note Cards" : "Note cards can be used for vocabulary, formulas, concepts, questions, etc. Take a stack of index cards with you to your session and have the students construct the cards during the session. Be sure to show the students how to make them and how to use them during your session. Write the cue or question on one side of the card and write the definition, description, or answer on the other side. Note cards are also portable and can be used as a quick review before tests and exams. Encourage the students to place relevant cards in a place where they can see them regularly to assist them in remembering important information.",
	"Learning Cells" : "To engage students in thinking about the content, encourage them to generate thought provoking questions, and check for understanding. Do the following: 1.students develop a list of questions and answers over course material; 2.form pairs; 3.student A asks the 1st question and student B answers. Student A offers corrections, clarification, additional information if needed; 4. Student B asks next question and student A answers; 5. Process continues until all questions are answered. Encourage students to ask more open ended questions and vary the types of questions.",
	"Venn Diagram" : "A venn diagram can be used to compare the similarities and differences between two concepts, systems or theories. Two overlapping circles are drawn on the board with each circle labeled as one of the two concepts. Students will then write the similarities in the overlapping portion and then differences in the outer portion of the circles. This is a good visual technique for reviewing similar yet contrasting concepts.",
	"Double Time Line" : "Construct  a very general timeline of events pertaining to the same time as the dates presented in the lecture. Present this general time line to the group and have them construct a duplicate time line pertaining to the lecture material directly below the one you have previously constructed.",
	

}
